# Generated by Django 4.1 on 2022-08-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
